### ISSUE TITLE
__builtin_debugtrap on clang/apple arm64

### ISSUE THREAD

**Issue by BAndysc** [scottt/debugbreak#21]
I do not know when it has changed, but in Apple clang 12 on Mac OS 11 on Apple M1
```
Apple clang version 12.0.5 (clang-1205.0.22.11)
Target: arm64-apple-darwin20.5.0
```

`__builtin_debugtrap` seems to be correctly generating assembly instructions

```
int main()
{
    __builtin_debugtrap();
    printf("abcn\n");
}

0000000100003f58 <_main>:
100003f58: fd 7b bf a9 	stp	x29, x30, [sp, #-16]!
100003f5c: fd 03 00 91 	mov	x29, sp
100003f60: 00 00 3e d4 	brk	#0xf000
100003f64: 00 00 00 90 	adrp	x0, #0
100003f68: 00 c0 3e 91 	add	x0, x0, #4016
100003f6c: 05 00 00 94 	bl	0x100003f80 <dyld_stub_binder+0x100003f80>
100003f70: 08 00 80 52 	mov	w8, #0
100003f74: e0 03 08 aa 	mov	x0, x8
100003f78: fd 7b c1 a8 	ldp	x29, x30, [sp], #16
100003f7c: c0 03 5f d6 	ret
```

And contrary to `__builtin_trap`, which is [currently used on apple arm](https://github.com/scottt/debugbreak/blob/master/debugbreak.h#L94), LLDB correctly allows to skip over this instruction (this is not the case in __builtin_trap). Therefore, can we change it to `__builtin_debugtrap`?

**Comment by scottt** [comment]
@BAndysn, the code currently uses `__builtin_trap()` on `__aarch64__ && __APPLE__` because of a previous external contribution (which I assume was tested).

I believe `__builtin_debugtrap()` always works correctly when it's available and has been available on the AARCH64 clang Apple ships for some time.

Could you test and see if the changes I made in this revision works correctly?
https://github.com/scottt/debugbreak/commit/5dcbe41d2bd4712c8014aa7e843723ad7b40fd74

**Comment by BAndysc** [comment]
Yes, it does work fine on Clang/Apple M1, both under lldb and Xcode (which uses lldb). Thanks! Can't test it for iPhone/iPad target tho.

**Comment by jwakely** [comment]
Using `__APPLE__` is wrong, because that macro is defined by GCC on macOS, but `__builtin_debugtrap()` is clang-specific and gives an error on GCC. Using a clang-specific built-in should be guarded by checking `__clang__` not `__APPLE__`.

Even better would be to check whether `__has_builtin` is defined and use `__has_builtin(__builtin_debugtrap)`.
